### ISSUE TITLE
csel.jpg not found

### ISSUE THREAD

**Issue by hbaslan** [doxakis/MachineLearningSharp#1]

**Comment by hbaslan** [comment]
csel.jpg not found

**Comment by doxakis** [comment]
Good catch! I fix it with a new image.

This project is not complete. I explore and I try different algorithms.

It looks like you have an interest on OCR (based on your public profile) (fork of tensorflow-ocr)

If you are using c#, you may want to check : https://github.com/doxakis/How-to-use-tesseract-ocr-4.0-with-csharp
If you are using python, check : https://github.com/sirfz/tesserocr

After some tests, we found that it is more accurate with the linux version of tesseract.
(I suggest to use python and run you code on linux.)

Use the version 4 of tesseract. It is LSTM-based. (on linux, you may have to compile it)
It is far more accurate than the version 3 and you don't have to do lot of image pre-processing.

With tesseract, you need to download Data Files (one data file per language you want to support)
Training is already done for you. (https://github.com/tesseract-ocr/tesseract/wiki/Data-Files)

If you want to speed up OCR, use https://github.com/tesseract-ocr/tessdata_fast instead of https://github.com/tesseract-ocr/tessdata. (available since September 15, 2017)
It uses only the new LSTM-based OCR engine. (faster and great accuracy)

**Comment by doxakis** [comment]
Hi, I will close the issue for now. Feel free to open it again.
